AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configuration for MARIAN Lambda function'

Parameters:
  LambdaLayerArn:
    Type: String
    Description: ARN of the Lambda layer containing dependencies

Resources:
  MarianFunctionConfiguration:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Marian
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/Marian-role-1wz8k7bw'
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200}
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_TABLE: email_metadata
          GMAIL_SECRET_ID: gmail/oauth/tokens
          ANTHROPIC_SECRET_ID: AntrhopicKey
      Tags:
        - Key: Project
          Value: MARIAN