AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for MARIAN email metadata'

Resources:
  EmailMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: email_metadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: email_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Project
          Value: MARIAN

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref EmailMetadataTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt EmailMetadataTable.Arn
