"""sync_email_schema

Revision ID: 65d82db06bc3
Revises: 
Create Date: 2024-12-29 21:48:34.914443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d82db06bc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(length=2000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('archived_date', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.Integer(), nullable=False),
    sa.Column('item_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(length=2000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('archived_date', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.Integer(), nullable=False),
    sa.Column('item_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('idx_catalog_items_deleted', 'catalog_items', ['deleted'], unique=False)
    op.create_index('idx_catalog_items_status', 'catalog_items', ['status'], unique=False)
    op.create_index('idx_catalog_items_title', 'catalog_items', ['title'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('threadId', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=500), server_default='', nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labelIds', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('from', sa.String(length=200), nullable=True),
    sa.Column('to', sa.String(length=200), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('cc', sa.Text(), server_default="''''", nullable=True),
    sa.Column('bcc', sa.Text(), server_default="''''", nullable=True),
    sa.Column('full_api_response', sa.Text(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gmail_labels',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('archived_date', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Integer(), nullable=False),
    sa.Column('modified_date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_tags_deleted', 'tags', ['deleted'], unique=False)
    op.create_table('asset_catalog_tags',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_catalog_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    op.create_table('asset_dependencies',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['asset_catalog_items.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['asset_catalog_items.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id', 'dependency_type')
    )
    op.create_table('catalog_tags',
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('catalog_item_id', 'tag_id')
    )
    op.create_table('email_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=100), nullable=False),
    sa.Column('threadId', sa.String(length=100), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('analyzed_date', sa.DateTime(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_reason', sa.Text(), nullable=False),
    sa.Column('action_needed', sa.Boolean(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('action_deadline', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=False),
    sa.Column('people_mentioned', sa.Text(), nullable=False),
    sa.Column('links_found', sa.Text(), nullable=False),
    sa.Column('links_display', sa.Text(), nullable=False),
    sa.Column('project', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('ref_docs', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('item_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Integer(), nullable=False),
    sa.Column('relationship_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relationships_source', 'item_relationships', ['source_id'], unique=False)
    op.create_index('idx_relationships_target', 'item_relationships', ['target_id'], unique=False)
    op.create_index('idx_relationships_type', 'item_relationships', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_relationships_type', table_name='item_relationships')
    op.drop_index('idx_relationships_target', table_name='item_relationships')
    op.drop_index('idx_relationships_source', table_name='item_relationships')
    op.drop_table('item_relationships')
    op.drop_table('email_analysis')
    op.drop_table('catalog_tags')
    op.drop_table('asset_dependencies')
    op.drop_table('asset_catalog_tags')
    op.drop_index('idx_tags_deleted', table_name='tags')
    op.drop_table('tags')
    op.drop_table('gmail_labels')
    op.drop_table('emails')
    op.drop_index('idx_catalog_items_title', table_name='catalog_items')
    op.drop_index('idx_catalog_items_status', table_name='catalog_items')
    op.drop_index('idx_catalog_items_deleted', table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('asset_catalog_items')
    # ### end Alembic commands ###
