# Database schema configuration
# This file defines database schema constants used across the application

email:
  columns:
    id:
      size: 100
      type: string
      description: "Email ID"
    thread_id:
      size: 100
      type: string
      description: "Thread ID"
    message_id:
      size: 100
      type: string
      description: "Message ID"
    subject:
      size: 500
      type: string
      description: "Email subject"
    from_address:
      size: 255
      type: string
      description: "Sender email address"
    to_address:
      size: 255
      type: string
      description: "Recipient email address"
    cc_address:
      size: 255
      type: string
      description: "CC recipients"
    bcc_address:
      size: 255
      type: string
      description: "BCC recipients"
  defaults:
    subject: ""
    body: null
    snippet: null
    from_address: null
    to_address: null
    cc_address: null
    bcc_address: null
    has_attachments: false
    is_read: false
    is_important: false
    api_response: "{}"
  validation:
    max_subject_length: 500
    max_from_length: 255
    max_to_length: 255
    max_cc_length: 255
    max_bcc_length: 255
  relationships:
    catalog_entry:
      type: "one_to_one"
      model: "CatalogEntry"
      back_populates: "email"
      cascade: "all, delete-orphan"

analysis:
  columns:
    sentiment:
      size: 20
      type: string
      description: "Sentiment analysis result"
    category:
      size: 50
      type: string
      description: "Email category"
    summary:
      size: 1000
      type: string
      description: "Email summary"
    priority:
      size: 20
      type: string
      description: "Email priority"
  defaults:
    sentiment: "neutral"
    category: "uncategorized"
    summary: null
    priority: "low"
  validation:
    valid_sentiments:
      - "positive"
      - "negative"
      - "neutral"
      - "mixed"
    valid_categories:
      - "work"
      - "personal"
      - "finance"
      - "social"
      - "support"
      - "uncategorized"
    valid_priorities:
      - "high"
      - "medium"
      - "low"
    max_summary_length: 1000

label:
  # Based on Gmail API Label resource:
  # https://developers.google.com/gmail/api/reference/rest/v1/users.labels#Label
  columns:
    id:
      size: 100
      type: string
      description: "Gmail API label ID"
    name:
      size: 255
      type: string
      description: "Display name of the label"
    message_list_visibility:
      size: 20
      type: string
      description: "Show/hide the label in the message list"
      nullable: true
    label_list_visibility:
      size: 20
      type: string
      description: "Show/hide the label in the label list"
      nullable: true
    type:
      size: 20
      type: string
      description: "Type of label (system/user)"
    color:
      size: 20
      type: string
      description: "Label color (hex code)"
      nullable: true
    background_color:
      size: 20
      type: string
      description: "Label background color (hex code)"
      nullable: true
    text_color:
      size: 20
      type: string
      description: "Label text color (hex code)"
      nullable: true
    messages_total:
      type: integer
      description: "Total number of messages with this label"
      nullable: true
    messages_unread:
      type: integer
      description: "Number of unread messages with this label"
      nullable: true
    threads_total:
      type: integer
      description: "Total number of threads with this label"
      nullable: true
    threads_unread:
      type: integer
      description: "Number of unread threads with this label"
      nullable: true
  defaults:
    name: ""
    type: "user"
    message_list_visibility: "show"
    label_list_visibility: "labelShow"
    messages_total: null
    messages_unread: null
    threads_total: null
    threads_unread: null
  validation:
    valid_types:
      - "system"
      - "user"
    valid_message_list_visibilities:
      - "show"
      - "hide"
    valid_label_list_visibilities:
      - "labelShow"
      - "labelShowIfUnread"
      - "labelHide"
