# Database schema configuration
# This file defines database schema constants used across the application

email:
  columns:
    id:
      size: 100
      type: string
      description: "Email ID"
    thread_id:
      size: 100
      type: string
      description: "Thread ID"
    message_id:
      size: 100
      type: string
      description: "Message ID"
    subject:
      size: 500
      type: string
      description: "Email subject"
    from_address:
      size: 255
      type: string
      description: "Sender email address"
    to_address:
      size: 255
      type: string
      description: "Recipient email address"
    cc_address:
      size: 255
      type: string
      description: "CC recipients"
    bcc_address:
      size: 255
      type: string
      description: "BCC recipients"
  defaults:
    subject: ""
    body: null
    snippet: null
    from_address: null
    to_address: null
    cc_address: null
    bcc_address: null
    has_attachments: false
    is_read: false
    is_important: false
    api_response: "{}"
  validation:
    max_subject_length: 500
    max_from_length: 255
    max_to_length: 255
    max_cc_length: 255
    max_bcc_length: 255

analysis:
  columns:
    sentiment:
      size: 20
      type: string
      description: "Sentiment analysis result"
    category:
      size: 50
      type: string
      description: "Email category"
    summary:
      size: 1000
      type: string
      description: "Email summary"
    priority:
      size: 20
      type: string
      description: "Email priority"
  defaults:
    sentiment: "neutral"
    category: "uncategorized"
    summary: null
    priority: "low"
  validation:
    valid_sentiments:
      - "positive"
      - "negative"
      - "neutral"
      - "mixed"
    valid_categories:
      - "work"
      - "personal"
      - "finance"
      - "social"
      - "support"
      - "uncategorized"
    valid_priorities:
      - "high"
      - "medium"
      - "low"
    max_summary_length: 1000

label:
  columns:
    label_id:
      size: 100
      type: string
      description: "Label ID"
    name:
      size: 255
      type: string
      description: "Label name"
    type:
      size: 20
      type: string
      description: "Label type"
  defaults:
    name: ""
    type: "user"
    message_list_visibility: "show"
    label_list_visibility: "labelShow"
    is_system: false
  validation:
    valid_types:
      - "system"
      - "user"
    valid_visibilities:
      - "show"
      - "hide"
    valid_label_visibilities:
      - "labelShow"
      - "labelHide"
