"""
Schema constants generated from schema.yaml.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generate_schema_constants.py
"""

from dataclasses import dataclass
from typing import Dict, List, Any, Optional

# Column sizes
COLUMN_SIZES: Dict[str, int] = {
    "EMAIL_ID": 100,
    "EMAIL_THREAD_ID": 100,
    "EMAIL_MESSAGE_ID": 100,
    "EMAIL_SUBJECT": 500,
    "EMAIL_FROM_ADDRESS": 255,
    "EMAIL_TO_ADDRESS": 255,
    "EMAIL_CC_ADDRESS": 255,
    "EMAIL_BCC_ADDRESS": 255,
    "EMAIL_SNIPPET": 1000,
    "EMAIL_HISTORY_ID": 100,
    "ANALYSIS_ID": 100,
    "ANALYSIS_EMAIL_ID": 100,
    "ANALYSIS_SUMMARY": 1000,
    "ANALYSIS_SENTIMENT": 20,
    "ANALYSIS_MODEL_VERSION": 50,
    "LABEL_ID": 100,
    "LABEL_NAME": 255,
    "LABEL_MESSAGE_LIST_VISIBILITY": 20,
    "LABEL_LABEL_LIST_VISIBILITY": 20,
    "LABEL_TYPE": 20,
    "LABEL_COLOR": 20,
}

# Default values

@dataclass
class EmailDefaults:
    """Default values for Email fields from schema.yaml."""
    subject: str = ""
    body: Optional[str] = None
    snippet: Optional[str] = None
    from_address: Optional[str] = None
    to_address: Optional[str] = None
    cc_address: Optional[str] = None
    bcc_address: Optional[str] = None
    has_attachments: bool = False
    is_read: bool = False
    is_important: bool = False
    labels: str = "[]"
    full_api_response: str = "{}"

@dataclass
class AnalysisDefaults:
    """Default values for Analysis fields from schema.yaml."""
    sentiment: str = "neutral"
    categories: str = "[]"
    summary: Optional[str] = None
    key_points: str = "[]"
    action_items: str = "[]"
    priority_score: Optional[str] = None
    confidence_score: Optional[str] = None
    model_version: Optional[str] = None
    analysis_metadata: str = "{}"

@dataclass
class LabelDefaults:
    """Default values for Label fields from schema.yaml."""
    name: str = ""
    type: str = "user"
    message_list_visibility: str = "show"
    label_list_visibility: str = "labelShow"
    messages_total: Optional[int] = None
    messages_unread: Optional[int] = None
    threads_total: Optional[int] = None
    threads_unread: Optional[int] = None

# Validation constants
VALID_SENTIMENTS = ['positive', 'negative', 'neutral', 'mixed']
VALID_CATEGORIES = ['work', 'personal', 'finance', 'social', 'support', 'uncategorized']
VALID_LABEL_TYPES = ['system', 'user']
VALID_VISIBILITIES = ['show', 'hide', 'labelShow', 'labelHide', 'labelShowIfUnread']