name: Database Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'models/**'
      - 'alembic/**'
      - 'config/schema.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'models/**'
      - 'alembic/**'
      - 'config/schema.yaml'

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check migrations
      run: ./scripts/ci/run_migrations.sh --check
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        ENV: test
        
  apply-migrations:
    needs: check-migrations
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Apply migrations
      run: ./scripts/ci/run_migrations.sh
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ENV: production
